### ISSUE TITLE
Thumbnail Sharpness

### ISSUE THREAD

**Issue by pvfreitas** [nk-crew/visual-portfolio#162] opened 2022-04-22 15:34 UTC
Hi, first of all, thanks for this amazing plugin, it’s helping me a lot as it’s super well built!

So I was wondering if there’s a way to improve the thumbnail sharpness of my galleries.
I created a Saved Layout, uploaded a few images, all 1800×1200, super sharp professional photographs. However, when seeing those images in the frontend they appear to be lacking a lot of sharpness.
I know the image will naturally lose sharpness because it’s being resized by the browser, but in this case, it looks almost blurry.
Is there a way to improve this?

**Comment by nk-o** [comment] 2022-05-05 08:31
Hey.

Can you provide an online example of your site, where I can see these blurry images?

I know there is a problem with Justified layout, in some cases images gets blurry.

**Comment by nk-o** [comment] 2022-05-05 11:53
Ah, I see it is duplicate of your topic - https://wordpress.org/support/topic/thumbnail-sharpness/

**Comment by pvfreitas** [comment] 2022-05-07 16:59
Sure. I'm using Windows 11, Google Chrome, 2560x1440 resolution.
The block that I mentioned is using a Masonry layout.
Please take a look at the screenshot that I mentioned https://imgbb.com/5YzCMMT and you'll see how it's showing up in my screen.
The top photo is how the plugin is rendering the photo. The bottom one I resized a <img> element using CSS
Thanks!

**Comment by nk-o** [comment] 2022-05-21 14:38
Hey. Unfortunately, I still can't see this bug on any of my devices. And I can't fix something, that I can't reproduce 🤷‍♂️

**Comment by nk-o** [comment] 2023-11-24 12:21
There is no possibility to reproduce this issue locally. If there is a reproduction guide, the issue can be fixed. I'll close it for now.

**Closed by nk-o** 2023-11-24 12:21 UTC
Labels: question
